package ui

import (
	"bytes"
	"strings"
	"testing"
)

// The substitution is a regex against an asset that gets regenerated by hand.
// If the two ever drift apart the replace silently does nothing and the mark
// keeps shipping whatever word is baked in — which is the whole bug this
// package exists to prevent. So: assert it actually replaced something.

func TestLockupShipsTheProductsName(t *testing.T) {
	got := string(Lockup(""))
	if !strings.Contains(got, tspans("LE VEILLEUR")) {
		t.Fatal("the shipped mark must spell LE VEILLEUR")
	}
	if !strings.Contains(got, `aria-label="le veilleur`) {
		t.Fatalf("the shipped mark must name itself in its accessible name")
	}
}

func TestLockupSubstitutesTheOperatorsHouse(t *testing.T) {
	got := string(Lockup("Example House"))
	if !strings.Contains(got, tspans("EXAMPLE HOUSE")) {
		t.Fatal("a configured house word must appear in the wordmark")
	}
	if strings.Contains(got, tspans("LE VEILLEUR")) {
		t.Fatal("the product's own word must be gone once a house replaced it")
	}
	if !strings.Contains(got, `aria-label="Example House — le veilleur"`) {
		t.Fatal("the accessible name must carry both the house and the product")
	}
	if bytes.Equal(Lockup("Example House"), Lockup("")) {
		t.Fatal("substitution did nothing: the regex no longer matches the asset")
	}
}

func TestLockupWithoutAHouseIsTheAssetItself(t *testing.T) {
	if !bytes.Equal(Lockup(""), Lockup("   ")) {
		t.Fatal("a blank house is no house")
	}
}
